sudo: required

language: cpp

compiler: gcc
dist: trusty

services:
  - docker

before_install:
  - docker pull wcsim/wcsim:build

install:
  - docker run --rm -v `pwd`:/root/HyperK/WCSim wcsim/wcsim:build /bin/sh -c " source /root/HyperK/env-WCSim.sh; cd /root/HyperK/WCSim; make clean; make rootcint; make;  ls"

script:
  - docker run --rm -v `pwd`:/root/HyperK/WCSim wcsim/wcsim:build /bin/sh -c "source /root/HyperK/env-WCSim.sh; cd /root/HyperK/WCSim; ./exe/bin/Linux-g++/WCSim WCSim.mac"
  - if [ -e ./exe/bin/Linux-g++/WCSim ]; then true; else false; fi
  - if [ -e wcsim.root ]; then true; else false; fi

notifications:
  email:
    recipients:
      - b.richards@qmul.ac.uk
      - erin.osullivan@fysik.su.se
    on_success: never # default: change
    on_failure: always # default: always